#!/usr/bin/env python3
"""
Generate docs/mastercrafted-handouts.md — a grouped list of /summonitem
commands for mastercrafted gear + crafted consumables, so GM Jason can copy
lines out and hand items to friends.

Read-only against the live eq2emu DB. Credentials come from docker/.env.

Definitions used here:
  * "mastercrafted gear" = crafted=1 items whose name starts with "Imbued "
    (the mastercrafted-with-charm line — the cleanest signal we have that
    distinguishes mastercrafted from plain handcrafted in this dataset).
  * "crafted consumables" = crafted=1 items of type Food, Bauble, or Thrown
    (food/drink, totems, ammo).
  * Dedup: rows with id >= 10_000_000 are client-version duplicates; skipped.
    Further deduped by LOWER(name) with MIN(id) winning.
  * Level buckets use required_level when > 0, else recommended_level, else 1.
"""

import os
import re
import sys
from collections import defaultdict
from pathlib import Path

import pymysql

REPO = Path(__file__).resolve().parent.parent
ENV = REPO / "docker" / ".env"
OUT = REPO / "docs" / "mastercrafted-handouts.md"

GEAR_TYPES = ("Weapon", "Armor", "Shield", "Ranged", "Thrown", "Bauble")
GEAR_TYPE_DISPLAY = {
    "Weapon": "Weapons",
    "Armor": "Armor",
    "Shield": "Shields",
    "Ranged": "Ranged",
    "Thrown": "Thrown",
    "Bauble": "Baubles",
}
BAND_LABELS = [
    (0, "Levels 1-9"),
    (1, "Levels 10-19"),
    (2, "Levels 20-29"),
    (3, "Levels 30-39"),
    (4, "Levels 40-49"),
    (5, "Levels 50-59"),
    (6, "Levels 60-69"),
    (7, "Levels 70-79"),
    (8, "Levels 80-89"),
    (9, "Levels 90+"),
]


def load_env():
    kv = {}
    for line in ENV.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        kv[k.strip()] = v.strip().strip('"').strip("'")
    return kv


def effective_level(req, rec):
    lvl = max(req or 0, rec or 0)
    return lvl if lvl > 0 else 1


def band_for(req, rec):
    lvl = effective_level(req, rec)
    if lvl >= 90:
        return 9
    return min(9, max(0, lvl // 10))


def fetch_rows(cur, sql):
    cur.execute(sql)
    return cur.fetchall()


def dedup(rows):
    """Keep first row for each lower(name); rows must be sorted by id."""
    seen = {}
    for r in rows:
        key = r["name"].lower()
        if key not in seen:
            seen[key] = r
    return list(seen.values())


def main():
    env = load_env()
    conn = pymysql.connect(
        host="127.0.0.1",
        port=3306,
        user="root",
        password=env["MARIADB_ROOT_PASSWORD"],
        database=env["MARIADB_DATABASE"],
        cursorclass=pymysql.cursors.DictCursor,
        charset="utf8mb4",
    )

    with conn.cursor() as cur:
        gear_types_in = ",".join(f"'{t}'" for t in GEAR_TYPES)
        gear_sql = f"""
            SELECT id, name, item_type, required_level, recommended_level
              FROM items
             WHERE crafted = 1
               AND id < 10000000
               AND name LIKE 'Imbued %'
               AND item_type IN ({gear_types_in})
             ORDER BY id
        """
        gear_rows = dedup(fetch_rows(cur, gear_sql))

        consumable_sql = """
            SELECT id, name, item_type, required_level, recommended_level
              FROM items
             WHERE crafted = 1
               AND id < 10000000
               AND item_type IN ('Food', 'Bauble', 'Thrown')
             ORDER BY id
        """
        consumable_rows = dedup(fetch_rows(cur, consumable_sql))

    buckets_gear = defaultdict(lambda: defaultdict(list))
    for r in gear_rows:
        b = band_for(r["required_level"], r["recommended_level"])
        buckets_gear[b][r["item_type"]].append(r)

    buckets_cons = defaultdict(lambda: defaultdict(list))
    for r in consumable_rows:
        b = band_for(r["required_level"], r["recommended_level"])
        buckets_cons[b][r["item_type"]].append(r)

    def command_line(r):
        lvl = effective_level(r["required_level"], r["recommended_level"])
        name = r["name"].strip()
        return f"/summonitem {r['id']:<8}  # {name} (lvl {lvl})"

    def code_block(rows):
        yield "```text"
        for r in rows:
            yield command_line(r)
        yield "```"

    out = []
    out.append("# Mastercrafted handout catalog")
    out.append("")
    out.append("Auto-generated by `scripts/gen-mastercrafted-handouts.py`. ")
    out.append("Re-run after DB changes.")
    out.append("")
    out.append("How to hand items out: each subsection below is a fenced code block &mdash; hover ")
    out.append("the block on GitHub to get a copy button. Paste a single line into the EQ2 client ")
    out.append("to summon one item, or paste multiple lines to summon many at once.")
    out.append("")
    out.append("- **To yourself**: `/summonitem <item_id>` &mdash; summons one into your bags.")
    out.append("- **To yourself, into the bank**: `/summonitem <item_id> 1 bank`.")
    out.append("- **Directly to another player**: `/giveitem <player_name> <item_id>`.")
    out.append("- **Give yourself coin**: `/player coins add plat 100` (or gold/silver/copper).")
    out.append("")
    out.append("Level shown is the item's required/recommended level. ")
    out.append("Items at level 1 have no requirement set in the DB.")
    out.append("")
    out.append("---")
    out.append("")

    out.append("## Mastercrafted gear (Imbued line)")
    out.append("")
    out.append(f"Total gear items: **{len(gear_rows)}**")
    out.append("")
    for b, label in BAND_LABELS:
        if b not in buckets_gear:
            continue
        band_items = buckets_gear[b]
        total = sum(len(v) for v in band_items.values())
        out.append(f"### {label} &mdash; {total} items")
        out.append("")
        for typ in GEAR_TYPES:
            if typ not in band_items:
                continue
            rows = sorted(band_items[typ], key=lambda r: (effective_level(r["required_level"], r["recommended_level"]), r["name"].lower()))
            out.append(f"#### {GEAR_TYPE_DISPLAY.get(typ, typ)} ({len(rows)})")
            out.append("")
            out.extend(code_block(rows))
            out.append("")

    out.append("---")
    out.append("")
    out.append("## Crafted consumables")
    out.append("")
    out.append(f"Total consumable items: **{len(consumable_rows)}**")
    out.append("")
    CONS_DISPLAY = {"Food": "Food & drink", "Bauble": "Totems & baubles", "Thrown": "Arrows & thrown"}
    for b, label in BAND_LABELS:
        if b not in buckets_cons:
            continue
        band_items = buckets_cons[b]
        total = sum(len(v) for v in band_items.values())
        out.append(f"### {label} &mdash; {total} items")
        out.append("")
        for typ in ("Food", "Bauble", "Thrown"):
            if typ not in band_items:
                continue
            rows = sorted(band_items[typ], key=lambda r: (effective_level(r["required_level"], r["recommended_level"]), r["name"].lower()))
            out.append(f"#### {CONS_DISPLAY[typ]} ({len(rows)})")
            out.append("")
            out.extend(code_block(rows))
            out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(gear_rows)} gear, {len(consumable_rows)} consumable)")


if __name__ == "__main__":
    main()
